# This is a basic workflow to help you get started with Actions

name: Deploy to Firebase

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Enables flutter environment setup
      - uses: subosito/flutter-action@v2.3.0
      
      # Get dependencies
      - name: Get flutter dependencies
        run: flutter pub get
        
      # Build web
      - name: Build Flutter Web 
        run: flutter build web --base-href=/flutter-portfolio-site/
        
      # Deploy
      - name: Deploy to GH Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: portfolio-dev
          build_dir: ./build/web/
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
